/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package apollo.Graphics;

import apollo.Entidades.Usuario;
import apollo.Listenners.tableListenner;
import apollo.Player.ListaDeReproducao;
import apollo.Player.Reprodutor;
import java.awt.Toolkit;

/**
 *
 * @author Leonardo Dias
 */
public class IUPrincipal extends javax.swing.JFrame{

    private static Usuario sessao = null;
    /**
     * Creates new form IUPrincipal
     * @param sessao
     */
    public IUPrincipal(Usuario sessao) {
        IUPrincipal.sessao = sessao;
        initComponents();
        setResizable(false);
        setVisible(true);
        setSize(236, 480);
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width-getWidth())/2, (Toolkit.getDefaultToolkit().getScreenSize().height-getHeight())/2);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        jLabelTrackName.setText("- -");
        jLabelTrackAutor.setText("- -");
        jLabelTrackTime.setText("00:00/- -:- -");
        jTableListaReproducao.getColumnModel().getColumn(1).setPreferredWidth(5);
        
        jTableListaReproducao.addMouseListener(new tableListenner());
        //FaixasDAO daofaixas = new FaixasDAO();
        ListaDeReproducao.iniciaLista();
        /*try {
            ListaDeReproducao.insereOutraLista(daofaixas.getListFaixaByAutor(""));
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanelFundo = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelTop = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaReproducao = new javax.swing.JTable();
        jLabelTrackName = new javax.swing.JLabel();
        jLabelTrackTime = new javax.swing.JLabel();
        jLabelTrackAutor = new javax.swing.JLabel();
        jPanelBot = new javax.swing.JPanel();
        btPrev = new javax.swing.JButton();
        btPlay = new javax.swing.JButton();
        btStop = new javax.swing.JButton();
        btNext = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuOptions = new javax.swing.JMenu();
        jMenuInsertTrack = new javax.swing.JMenuItem();
        jMenuFatura = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFundo.setBackground(new java.awt.Color(250, 250, 250));

        jPanelTop.setBackground(new java.awt.Color(250, 250, 250));

        jTableListaReproducao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Duração"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaReproducao.getTableHeader().setResizingAllowed(false);
        jTableListaReproducao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableListaReproducao);

        jLabelTrackName.setText("Nome da Musica");

        jLabelTrackTime.setText("00:00/00:00");

        jLabelTrackAutor.setText("Nome do Autor");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTrackName)
                    .addComponent(jLabelTrackTime)
                    .addComponent(jLabelTrackAutor))
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelTrackName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTrackAutor)
                .addGap(4, 4, 4)
                .addComponent(jLabelTrackTime)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBot.setBackground(new java.awt.Color(250, 250, 250));

        btPrev.setBackground(new java.awt.Color(250, 250, 250));
        btPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btPrev.png"))); // NOI18N
        btPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrevActionPerformed(evt);
            }
        });

        btPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btPlay.png"))); // NOI18N
        btPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlayActionPerformed(evt);
            }
        });

        btStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btStop.png"))); // NOI18N
        btStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStopActionPerformed(evt);
            }
        });

        btNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btNext.png"))); // NOI18N
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotLayout = new javax.swing.GroupLayout(jPanelBot);
        jPanelBot.setLayout(jPanelBotLayout);
        jPanelBotLayout.setHorizontalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btStop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelBotLayout.setVerticalGroup(
            jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btNext, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btPrev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPlay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addComponent(jPanelBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFundoLayout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jMenuBar.setBackground(new java.awt.Color(250, 250, 250));

        jMenuOptions.setText("Opções");

        jMenuInsertTrack.setText("Inserir Faixa");
        jMenuInsertTrack.setToolTipText("");
        jMenuInsertTrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInsertTrackActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuInsertTrack);

        jMenuFatura.setText("Fatura");
        jMenuFatura.setToolTipText("");
        jMenuFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFaturaActionPerformed(evt);
            }
        });
        jMenuOptions.add(jMenuFatura);

        jMenuBar.add(jMenuOptions);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        ListaDeReproducao.proxMusica();
    }//GEN-LAST:event_btNextActionPerformed

    private void btStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStopActionPerformed
        ListaDeReproducao.parar();
    }//GEN-LAST:event_btStopActionPerformed

    private void btPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlayActionPerformed
        if(Reprodutor.getStatus()==Reprodutor.STOPPED)
            ListaDeReproducao.tocar();
        else if(Reprodutor.getStatus()==Reprodutor.PLAYING)
            ListaDeReproducao.pause();
        else if(Reprodutor.getStatus()==Reprodutor.PAUSED)
            ListaDeReproducao.continuar();        
    }//GEN-LAST:event_btPlayActionPerformed

    private void btPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrevActionPerformed
        ListaDeReproducao.antMusica();
    }//GEN-LAST:event_btPrevActionPerformed

    private void jMenuInsertTrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInsertTrackActionPerformed
        new IUInsereFaixa();
    }//GEN-LAST:event_jMenuInsertTrackActionPerformed

    private void jMenuFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFaturaActionPerformed
        new IURelatorio(sessao);
    }//GEN-LAST:event_jMenuFaturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNext;
    private javax.swing.JButton btPlay;
    private javax.swing.JButton btPrev;
    private javax.swing.JButton btStop;
    private static javax.swing.JLabel jLabelTrackAutor;
    private static javax.swing.JLabel jLabelTrackName;
    private static javax.swing.JLabel jLabelTrackTime;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuFatura;
    private javax.swing.JMenuItem jMenuInsertTrack;
    private javax.swing.JMenu jMenuOptions;
    private javax.swing.JPanel jPanelBot;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelTop;
    private static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableListaReproducao;
    // End of variables declaration//GEN-END:variables

    
    public static void setLabelTrackName(String nome){
        jLabelTrackName.setText(nome);
    }
    
    public static void setLabelTrackTime(String time){
        jLabelTrackTime.setText(time);
    }
    
    public static void setLabelTrackAutor(String time){
        jLabelTrackAutor.setText(time);
    }
    
    public static String getLabelTrackTime(){
        return jLabelTrackTime.getText();
    }
    
    public static void setJProgressBarLenght(int lenght){
        jProgressBar1.setSize(0, lenght);
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(false);
    }
    
    public static void updateJProgressBar(){
        jProgressBar1.setValue(Reprodutor.getTime()*100/Reprodutor.getTimeLenght());
    }
    
    public static void setJProgressBarZero(){
        jProgressBar1.setValue(0);
    }
    
    public static Usuario getSessao(){
        return sessao;
    }
}
